### ISSUE TITLE
Oauth refresh

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#33] opened 2019-09-25 22:09 UTC
**Describe the bug**
Refreshing tokens appears to not work. You can back an `invalid_grant` oauth error. The error happens https://github.com/LedgerSync/ledger_sync/blob/master/lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb#L70

For me, I was experiencing this when trying to refresh the connection to an expired ledger here: https://github.com/LedgerSync/ledger_sync/blob/master/lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb#L70

**To Reproduce**
0. Create a ledger locally with the following data
```
{"id"=>"ldgr_4Gx3t2XrtWlTigalZNnw", "kind"=>"quickbooks_online", "organization_id"=>"org_7wFHRynYgK6p98W7CoKSNQ", "access_token"=>"eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..M8lLiFuEFx24MfHNqM3eow.U54CR7_7xIxkRQ1C0pLUCVrlpd2vsRzDlMkNax8CpqpU5U6GBvlRelhCOx-reJrIxxv65kvYhizwARed1UPi-tA7aEXmY-r6iD1HndnPnEoRvcUrcGZn84zaUKHGQscJqq8_09woflBnsKR78YO_l9dV-vJNITyTzi2uQ_efU8bLoB8KYgLISisqtHIfdr8gd_7X4mYWO7GqVC8sco64ZaaZADEIIbU60pXQqWjyk6OBijqp58xDN2_RMxbdsq1_xZrzEsEHpiMYZFlpBhBkoSmBlXFZZOLP68hCMbmMs7k0HDT2aHVdEYq9NyrQD5JbGK6X9LXgGRLERsGlYMlzsIwKge7ZXwbY0vfL1IPbJp64f3cR7QrHLZHqZ-rKCuWXJ3pPk6Crd5_mpS0EX8ut8sSmyz459g8oCfWzlOQ5mtL1hDz0VxaF8-P4NjfKtyFDqNILY30GOmz6190RJLwfJxvDBExsRJz_FWLEwM6WUyLIQibq6BPDgf4A3tm_IeFkuWuIWv9xtlRiqnAzZ0vi8CpPxn3YMmZhMU0kIArbQsc-DVaPWOD5EjwutczmbuGTaVcrnlNIul26OOAyTZc7fjUEDaZ29x0IL_FDy0U96Usy85o46okdoARMBk9uQ5Uen3dTRV0wHpFWYrnIr1uISjayzpWQElkmZBYEYoct9OS5hpE1v9dYfx9uQ4q_LqHvzBqFhZeQY_tGR4lXpHzbV5oAe0_bYwu5ATSStYr9c1c.WkpwMRYMgWsgGpqGPAi8Uw", "refresh_token"=>"AB11577557640Va2vIgkY1fCrUWHkS5Uxs5lqB2uI1r413J0vw", "expires_at"=>Wed, 18 Sep 2019 19:27:20 UTC +00:00, "data"=>{"code"=>"AB115688316006lCIzwHqbN2Ml4JyaOMb8RYNYVMTt1Imp7YL4", "state"=>"46522bc17eda69069649ec1f", "realm_id"=>"4620816365006687440", "response"=>{"expires_at"=>1568834840, "token_type"=>"bearer", "access_token"=>"eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..M8lLiFuEFx24MfHNqM3eow.U54CR7_7xIxkRQ1C0pLUCVrlpd2vsRzDlMkNax8CpqpU5U6GBvlRelhCOx-reJrIxxv65kvYhizwARed1UPi-tA7aEXmY-r6iD1HndnPnEoRvcUrcGZn84zaUKHGQscJqq8_09woflBnsKR78YO_l9dV-vJNITyTzi2uQ_efU8bLoB8KYgLISisqtHIfdr8gd_7X4mYWO7GqVC8sco64ZaaZADEIIbU60pXQqWjyk6OBijqp58xDN2_RMxbdsq1_xZrzEsEHpiMYZFlpBhBkoSmBlXFZZOLP68hCMbmMs7k0HDT2aHVdEYq9NyrQD5JbGK6X9LXgGRLERsGlYMlzsIwKge7ZXwbY0vfL1IPbJp64f3cR7QrHLZHqZ-rKCuWXJ3pPk6Crd5_mpS0EX8ut8sSmyz459g8oCfWzlOQ5mtL1hDz0VxaF8-P4NjfKtyFDqNILY30GOmz6190RJLwfJxvDBExsRJz_FWLEwM6WUyLIQibq6BPDgf4A3tm_IeFkuWuIWv9xtlRiqnAzZ0vi8CpPxn3YMmZhMU0kIArbQsc-DVaPWOD5EjwutczmbuGTaVcrnlNIul26OOAyTZc7fjUEDaZ29x0IL_FDy0U96Usy85o46okdoARMBk9uQ5Uen3dTRV0wHpFWYrnIr1uISjayzpWQElkmZBYEYoct9OS5hpE1v9dYfx9uQ4q_LqHvzBqFhZeQY_tGR4lXpHzbV5oAe0_bYwu5ATSStYr9c1c.WkpwMRYMgWsgGpqGPAi8Uw", "refresh_token"=>"AB11577557640Va2vIgkY1fCrUWHkS5Uxs5lqB2uI1r413J0vw", "x_refresh_token_expires_in"=>8726400}}, "connected_by"=>nil, "disconnected_by"=>nil, "disconnected_at"=>nil, "created_at"=>Wed, 18 Sep 2019 18:27:20 UTC +00:00, "updated_at"=>Wed, 18 Sep 2019 18:27:20 UTC +00:00}
```
1. Go to refresh ledger
![image](https://user-images.githubusercontent.com/4755444/65643266-2338c900-dfa6-11e9-880e-4f4fbfdf5e89.png)

2. Click refresh

**Expected behavior**
The refreshing should work

**Possibly helpful**
https://help.developer.intuit.com/s/question/0D50f00004uZSEfCAO/more-info-in-invalidgrant-error

**Comment by ryanwjackson** [comment] 2019-09-25 23:04
We should add a test to make sure changes in adaptor tokens are persisted (assuming we don’t have one). 

Trying to nail this down with a test.

**Comment by jozefvaclavik** [comment] 2019-09-26 04:53
Don't think this is an issue with `ledger_sync`.

1. have an expired `access_token` in rails app
2. create adaptor in `ledger_sync` (`./bin/console`)
```
adaptor = LedgerSync::Adaptors::QuickBooksOnline::Adaptor.new(
  access_token: "EXPIRED ACCESS TOKEN",
  refresh_token: 'LATEST REFRESH TOKEN FROM RAILS',
  realm_id: '...',
  client_id: '...',
  client_secret: '...',
  test: true
)
```
and do `adaptor.refresh!`. this will pass and update `access_token` and `refresh_token`
3. go back to rails and click `Refresh` - it will crash with `invalid_grant`
4. open rails console and update `refresh_token` on a ledger by the one you got from `adaptor.refresh!`
5. try `Refresh` again, and it will pass

**Comment by jozefvaclavik** [comment] 2019-09-26 09:31
https://github.com/LedgerSync/ledger_sync/pull/34

**Comment by ryanwjackson** [comment] 2019-09-26 18:48
@mattgmarcus I'm trying to pin down how you got this error in the first place.  I understand these steps to reproduce, but that flow should not exist in the app.  If you do manually refresh or something from the console, then we would not have the updated keys stored so it would error out.

As an intermediate solution, we can listen for the `invalid_grant` and then just redirect them to connect again.  This discussion can be moved to LedgerSync/rails_app, and we will need to likely allow for the ability to update credentials for existing ledgers.

**Comment by ryanwjackson** [comment] 2019-09-27 00:38
Closing this in favor of https://github.com/LedgerSync/rails_app/issues/54, as it looks like an issue with https://github.com/LedgerSync/rails_app, not this library.

**Closed by ryanwjackson** 2019-09-27 00:38 UTC
Labels: bug
